### ISSUE TITLE
Possiblity to add random to own mod?

### ISSUE THREAD

**Issue by Froddish** [Dastan21/LC_RandomSounds#1]
Hello!

I have "made" a simple mod for me and my friends which replace sounds using customsounds, and that was fairly easy to make.

- manifest.json
- README.md
- CHANGELOG.md (Optional)
- BepInEx
    - plugins
        - CustomSounds
            - <YourSoundPackName>
                - [Insert All Audio Files Here]

is it possible to have same folder structure but with randomsounds instead? (ofc as dependency in manifest aswell)

**Comment by Dastan21** [comment]
Fixed hierarchy on thunderstore.io 👍
