### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by MrBaldyMod** [Dastan21/LC_RandomSounds#2]
Failing to load. It is the latest version although it says 1.0.0. Here's the log:

`[Info   :   BepInEx] Loading [RandomSounds 1.0.0]
[Error  : Unity Log] TypeLoadException: Failure has occurred while loading a type.
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()`

**Comment by Dastan21** [comment]
You need LC_API. I f*cked up the dependencies and put `LCSoundTool` instead of `LC_API` on Thunderstore.
