### ISSUE TITLE
Sync problem

### ISSUE THREAD

**Issue by TenMarFly** [Dastan21/LC_RandomSounds#3]
Hello,
I have a problem with syncing most files like **0DaysLeftAlert**, **Mic files** but the **WallRumbleVoice** does work.
I tried switching the files around from my mod to your mod and then to the profile plugins folder and still nothing.
Could you please help me if I'm doing something wrong?
![example](https://github.com/Dastan21/LC_RandomSounds/assets/171619063/4e994c46-ee9f-49a0-9b8e-cfa1dad13cd8)

**Comment by TenMarFly** [comment]
![2](https://github.com/Dastan21/LC_RandomSounds/assets/171619063/3d4858da-ce57-4c67-ac9b-1f4207210b2b)

![1](https://github.com/Dastan21/LC_RandomSounds/assets/171619063/492be46e-4a75-4193-aa58-a5624600f5e8)

Extra photo of how I have the files in the **RandomsSounds** folder

**Comment by Dastan21** [comment]
v50 caused lots of issues

**Comment by TenMarFly** [comment]
Any plans on updating it?

**Comment by Dastan21** [comment]
I can't debug/dev on the mod since the v50 update idk why, so probably not
